### ISSUE TITLE
How to know the largest file size that is free to upload?

### ISSUE THREAD

**Issue by macaujack** [ardriveapp/turbo-sdk#215]
I'm building an APP that leverages Turbo to upload some files to Arweave.

When I use ArDrive to upload a file with size <= 100,000 bytes, I can get a hint message, telling me that this transaction is free thanks to Turbo. This is shown in the following screenshot.

![image](https://github.com/user-attachments/assets/e3381892-17bc-40f1-882e-3ea7647fb6a4)

I don't want to hard-code the 100,000 bytes size limit in my source code. I'm wondering if there's a JSON API endpoint (or something like this) that can respond me with the file size limit that is free to upload. Thanks!

**Comment by dtfiedler** [comment]
The https://turbo.ardrive.io/info endpoint provides a `freeUploadLimitBytes` attribute that specifies the free upload limit for a given bundler. 

https://github.com/ardriveapp/turbo-upload-service/blob/main/src/routes/info.ts#L23-L40

**Comment by macaujack** [comment]
Thanks this is exactly what I want. Just one more question. According to both the [Swagger API docs](https://upload.ardrive.io/api-docs) and the [API docs in raw JSON](https://upload.ardrive.io/openapi.json), the JSON response of this endpoint only contains 3 fields, `version`, `addresses`, `gateway`. The `freeUploadLimitBytes` field is not documented, though it actually exists in the JSON response. Is this because the documentation is not updated?

**Comment by dtfiedler** [comment]
Correct, just out of date. We'll put some effort into aligning the API docs with the latest when the team is back from the holidays. We also welcome a PR if you're up for it!
