### ISSUE TITLE
feat (web): accepting U token transfers

### ISSUE THREAD

**Issue by l-silvestre** [ardriveapp/turbo-sdk#79]
**Please Describe The Problem To Be Solved**
It would be good to hava support for buying and transfering the U token with turbo created wallets. 

**(Optional): Suggest A Solution**
Ardrive could provide liquidity for u allowing for turbo and allow created wallets to hold and transfer the token.

**Comment by dtfiedler** [comment]
Hi @l-silvestre 

Thank you for the submission! A few clarifying points before we dive into desired expectations:
- _support for buying and transfering the U_ - from the [$U docs](https://github.com/permaweb/U/blob/main/contracts/DEVELOPER-GUIDE.md), any $U interactions other than `mint` must go through a warp-sequencer. Right now, that traffic is then split 50/50 between Irys/Turbo bundlers. This SDK is intended to upload signed data items to Turbo and does not communicate with warp-sequencers in any way.

- _with turbo-created-wallets_ - this SDK (nor any Turbo Services) provide tooling for creating wallets. the SDK allows you to provide an Arweave JWK for various features like checking balance, topping up, and uploading raw files (via `.uploadFile()`). It also supports uploading signed data items (via `.uploadSignedDataItems()`) from any wallet supported by [arbundles](https://github.com/Irys-xyz/arbundles), so long as they are below the free upload limit (currently anything <500KiB). We do not currently support payments/top-ups for non-arweave wallets at this time.

So - regarding your desired expectations, I’m not sure the functionality described is a good fit for the Turbo SDK. There are various other tools/teams we are working to integrate with Turbo, and if you have any integrations you are looking for we are happy to help support in any way we can.
